dist: xenial
language: python
branches:
  only:
    - master
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=mypy
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
install:
  - pip install pipenv pytest tox mypy flake8
script:
  - tox 
