language: python
matrix:
  include:
    - name: "Python 3.6"
      python: 3.6
    - name: "Python 3.7"
      python: 3.7
      dist: xenial
before_install:
  - pip install pipenv pytest tox
script:
  - tox 
