[tool.poetry]
name = "bcompier-engine"
version = "0.1.0"
description = "A new, faster, more efficient, more modular back end for datamap tools and  interfaces."
authors = ["Matt Lemon"]

[tool.poetry.dependencies]
python = "^3.7.3"
openpyxl = "^2.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pdbpp = "^0.10.0"
ptipython = "^1.0.1"
flake8 = "^3.7.7"
black = "^19.3.b0"
mypy = "^0.711"
